development:
  adapter: postgresql
  database: insanity_plea_studios_dev
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: insanity_plea_studios_test
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  
production:
  adapter: postgresql
  database: insanity_plea_studios_production
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000